### ISSUE TITLE
New release on pip?

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/genologics#118]
Are you guys planning a new release on the cheese shop? :smiley: 

I'm using some new functionality and it would be nice to just point to a pip release, it's fine if you just upload it under a `beta` tag

**Comment by Galithil** [comment]
I'm not really sure what you're talking about. You're saying that we should upload the latest changes there, is that right ?

**Comment by robinandeer** [comment]
Yeah, exactly -  new release

Seems like the latest tag `v0.2.3` isn't on Pypi, no? The latest there is `2.1.0` or something.

**Comment by Galithil** [comment]
@pekrau any idea who did that last ? latest version there was put there in 2013.

**Comment by pekrau** [comment]
I have a feeling it might have been Roman Valls, or possibly Guillermo.

**Comment by robinandeer** [comment]
Probably @brainstorm

> Package Index Maintainer: brainstorm
https://pypi.python.org/pypi/genologics/0.2.1

**Comment by Galithil** [comment]
I can see Roman's name in the setup script. 
The bad news is that our version scheme, governed by git tags, does not follow PEP440, so pypi refuses it straight away. 
I like having git taking care of that though :/

**Comment by brainstorm** [comment]
I recall dutifully giving admin role to that pypi repo to the user `scilifelab` and then giving that password away... to @pekrau? @guillermo-carrasco? :-S

**Comment by brainstorm** [comment]
Also tried to send a "reset password" for `scilifelab`... but both my email account and guillermo's got deactivated since we left :/

**Comment by Galithil** [comment]
Well, we can't upload it anyway because of the version problem, and I don't have time to spare for that ATM, so ...

**Comment by Galithil** [comment]
the pip package is now being updated  for new releases.
