### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/genologics#133]
I'm having issues with specifically UDF caching in persistent sessions
It seems when I'm fetching information on the first sample everything works as expected. Then when I get information for subsequent samples the interface retains the UDF:s for the first sample.

Directly accessing the API returns the expected values

**Comment by astatham** [comment]
Are you using the pip version or github version?

**Comment by robinandeer** [comment]
Was that the thing...? genologics==0.2.1

**Comment by astatham** [comment]
Yeah the pip version has been broken for months - try

pip install https://github.com/SciLifeLab/genologics/tarball/master

**Comment by robinandeer** [comment]
I think it did the trick :+1: - thanks @astatham!

It would be super if this working version was available on pip
Perhaps skip the fancy "git version" stuff and just update on Pypi?

**Comment by astatham** [comment]
Looks like they lost the password, ha
https://github.com/SciLifeLab/genologics/issues/118

**Comment by Galithil** [comment]
Yep, we did. But i'm surprised Robin does not remember that issue, since he's the one who opened it...

Also, pip does not like the github version format. I like it because I'm sure to always work with the latest version. but I guess you're right, we should have a decent versioning system and host the right version on pypi...

**Comment by robinandeer** [comment]
I'm sorry @Galithil, I do remember - losing the password is certainly not on you :)

Maybe it doesn't matter if you rename the PyPi package and upload it under a new account, I could do that :)

**Comment by Galithil** [comment]
Okay, I have a fix for the versioning system, so it should work for Pypi, but since I still don't have the password, it's going to be a pain to actually upload it there...

**Comment by Galithil** [comment]
pip version has been updated and will be in the future, closing this.

**Comment by robinandeer** [comment]
yes, the current upload has been working great, thanks!
