### ISSUE TITLE
questions about BASEURL in config file

### ISSUE THREAD

**Issue by MAKO-Bioinfo** [SciLifeLab/genologics#147]
Hi all,
I apologize if this is not the place to ask questions. If so, please direct me to the right place. I found my BASEURL has an extra "clarity/profile" for some reason. It return 
In [3]: BASEURI
Out[3]: 'https://mako.claritylims.com/clarity/profile'

where it should be just 
https://mako.claritylims.com/

My genologics.conf file looks ok. Here's what it looks like. 

[genologics]
BASEURI=https://mako.claritylims.com:8443
USERNAME=xxxx
PASSWORD=XXXXXXXXXXXX
[logging]
MAIN_LOG=/Users/jack/Applications/log

Has any of you seen this yet? Any comments are very appreciated.

**Comment by Galithil** [comment]
I haven't seen that happen, it looks like there is some redirecting going on, and it's probably due to one of your network settings. 

Which version of Clarity Lims are you using ?

What do you see when you visit https://mako.claritylims.com:8443/api/v2/ ?

**Comment by MAKO-Bioinfo** [comment]
Hi Dennis,

Thank you for the quick response. We have version 4.0.9.46. I tried your method but still the same. I agree it seems like the redirecting has some issue and I might have to consult with my IT people here. Thank you again!

Jack

[cid:CFDD4B8D-70B5-424D-BB23-27FF499A5074]
--------------------------------------------------------
Jack Yen
Mako Medical Laboratories

8461 Garvey Drive,

Raleigh NC 27616

E-mail: jyen@makomedical.com

Mobile: 314-214-5776
makomedical.com<http://makomedical.com/>

HIPAA Privacy Notification: This message and accompanying documents are covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521<tel:2510-2521>, and contain information intended for the specified individual(s) only. This information is confidential. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. If you have received this communication in error, please notify us immediately by e-mail and delete the original message.



From: Denis Moreno
Reply-To: SciLifeLab/genologics
Date: Friday, March 11, 2016 at 10:53 AM
To: SciLifeLab/genologics
Cc: Jack
Subject: Re: [genologics] questions about BASEURL in config file (#147)


I haven't seen that happen, it looks like there is some redirecting going on, and it's probably due to one of your network settings.

Which version of Clarity Lims are you using ?

What do you see when you visit https://mako.claritylims.com:8443/api/v2/ ?

**Comment by Galithil** [comment]
Unfortunately, we are still using 3.5, so I cannot test with your
conditions.

You might want to check if there isn't another configuration file taking
precedence over the one you showed me, look at config.py to see the valid
files.

I was suggesting to visit the address I gave you with your browser, to
ensure that this is the correct API endpoint, not to use it in the
configuration file. Could you try that and confirm that you reach an API
endpoint ?
Thanks

Denis

**Comment by MAKO-Bioinfo** [comment]
Do I have to "refresh" the genologics.conf file in order to see the change? If yes how do I do that? Thanks again.

**Comment by MAKO-Bioinfo** [comment]
I figured it out. I took a close look of the config.py file and found it's looking through all possible genologics config file and whichever found first will be use. ~/.genologicsrc was the first one it look and after I change that one with the correct BASEURI everything works properly :)

**Comment by Galithil** [comment]
Multiple configuration files, Issue closed.
