### ISSUE TITLE
Meetup at Genologics UGM in barcelona

### ISSUE THREAD

**Issue by tcezard** [SciLifeLab/genologics#150]
I'm not sure it is the best place to discuss this but a colleague and I will be in the UGM in May and I think this is a good opportunity to meet with developer and users of this API and discuss future developments.
I'll be in Barcelona from the 18th to the 21th of May and am happy to meet during or outside the UGM

Cheers
Tim

**Comment by Galithil** [comment]
I'll be at the UGM as well. I don't think we'll have an issue meeting at the UGM. Other meetings might have to go through @vezzi first.

**Comment by Galithil** [comment]
I've had a talk with @vezzi and it looks like my hands are free on this. 
Are you going to attend the Thursday pre-meeting at 09:00 ? This looks like the perfect time to talk about this.

**Comment by tcezard** [comment]
Yes I will be there.
