### ISSUE TITLE
Change to StepActions

### ISSUE THREAD

**Issue by tcezard** [SciLifeLab/genologics#151]
Hi,
I need to rework the way Step stores actions and that might results in backward incompatible changes to the API.
I was wondering how much this would affect you and the potential users of the API as it seems to be still work in progress
Cheers
Tim

**Comment by Galithil** [comment]
Yes, that would affect us as we use the step actions to access the
escalated samples. However, if your implementation still gives me access to
what I want, I probably can rewrite the concerned scripts anyway.
