### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by juliambrosman** [SciLifeLab/genologics#159]
Hi--

I'm testing this in a python3 environment and am running into some issues.

I was wondering if this package is currently intended to be compatible with python3 and if not, if you intend to make it so?  (I noticed this line: https://github.com/SciLifeLab/genologics/blob/master/genologics/lims.py#L15)

Thanks!

**Comment by tcezard** [comment]
I'm running it with python 3 with no issues
Could you describe the problem?

**Comment by juliambrosman** [comment]
That's good to know.

So far it's an error with configparser.
Input:
```
from genologics.lims import Lims
from genologics.entities import *

from genologics.config import BASEURI, USERNAME, PASSWORD

lims = Lims(BASEURI, USERNAME, PASSWORD)
```

output:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-ce76de6e8110> in <module>()
      6 from genologics.entities import *
      7 
----> 8 from genologics.config import BASEURI, USERNAME, PASSWORD
      9 
     10 lims = Lims(BASEURI, USERNAME, PASSWORD)

//anaconda/envs/py3/lib/python3.5/site-packages/genologics/config.py in <module>()
      3 import warnings
      4 
----> 5 import ConfigParser
      6 
      7 '''

ImportError: No module named 'ConfigParser'
```

Having trouble installing configparser in my python3.5 env, so just wanted to make sure that things will work when I can get all the libraries straight.  This is my first morning using python3, so I anticipate some growing pains.

Thanks.

**Comment by tcezard** [comment]
I didn't migrate the genologics.config to python3 and indeed ConfigParser is not part of python3 core library anymore.

You should still be able to use the Lims object without the config provided you specify the expected parameters to it (baseuri, username, password).

I'm using python 3.4 and have not tested with 3.5 so there might be some issues

**Comment by juliambrosman** [comment]
Sounds good, thanks for your help!
