### ISSUE TITLE
Split entities in two

### ISSUE THREAD

**Issue by tcezard** [SciLifeLab/genologics#170]
Hi
I want to split entities.py into entities and descriptors
I don't think it should affect anybody as the descriptors should not be used outside of the entities.
I'm not sure what to do with SampleHistory: should it stay in entities?

Thank

**Comment by Galithil** [comment]
I guess so, yes. It's heavily used by our main data extraction script, but
it's probably not that useful to you, and it has a lot of underlying logic
that is not pure xml reading, so I think it should stay in entities.
