### ISSUE TITLE
separating core API from site specific logic

### ISSUE THREAD

**Issue by tcezard** [SciLifeLab/genologics#171]
I was wondering what people though about the fact that the current repo contains the core library in the genologics directory and some scripts that are specific to SciLifeLab in the scripts.
My preference would be to separate the core code from any logic specific to a site.
This would allow the module to be more stable and easier to understand.
However I realise that there might be lots of things depending on the scripts and it might be non trivial to move them somewhere else.

Is it something you'd be willing to do?

**Comment by Galithil** [comment]
This is being taken care of in
https://github.com/SciLifeLab/genologics/pull/172
