### ISSUE TITLE
versionning issue

### ISSUE THREAD

**Issue by catherineleroyinivata** [SciLifeLab/genologics#188]
Hi, 

We have installed genologics 0.3.8 on all our servers (same as my computer now). 

**On our test us :** 
pip freeze | grep genologics ====> 0.3.8.post0 
Line 21 of /usr/lib/python2.6/site-packages/genologics/lims.py ====>if version_info[0]
and that works fine
(same as my computer)

**On our prod uk :** 
pip freeze | grep genologics ===> genologics==0.3.8.post0 
line 21 of file /usr/lib/python2.6/site-packages/genologics/lims.py ===> if version_info.major == 2: 
There when I run my script I get the following error : 

get the following error with the generate_metadata.py script : 
File "/usr/lib/python2.6/site-packages/genologics/lims.py", line 21, in <module> 
if version_info.major == 2: 
AttributeError: 'tuple' object has no attribute 'major'

Would you have any idea why that is? 

Thanks a lot for your help.
Catherine

**Comment by Galithil** [comment]
This was corrected in 3.9 :
https://github.com/Galithil/genologics/commit/1d19bc96a9e74b9d8fd5ba9824281626797e1b0e

The latest version is 3.10.
My guess is that you have something other than 0.3.8, maybe some additional
commits on test us.
