### ISSUE TITLE
Create new samples

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/genologics#189]
Hi guys!

I was wondering how it would be possible to create new samples using the REST API. I got it working using this package but it required some hacking. Perhaps I'm missing something.. Are you using the API to do something like that?

This is briefly my approach:

1. The API needs a "location" reference with a container on sample level so I borrow some code from `create` and add the extra stuff in the XML code:

```python
lims_sample = Sample(lims=lims, _create_new=True)
uhmmm = "{}:{}".format(Sample._PREFIX, Sample.__name__.lower())
lims_sample.root = ElementTree.Element(nsmap(uhmmm))

lims_sample.name = name
lims_sample.project = lims_project
location = ElementTree.SubElement(lims_sample.root, 'location')
ElementTree.SubElement(location, 'container', dict(uri=lims_container.uri))
position_element = ElementTree.SubElement(location, 'value')
position_element.text = position
```

2. To save a sample you need to use the "smp:samplecreation" tag (or whatever it's called) so I have to modify the data string before posting:

```python
data = lims.tostring(ElementTree.ElementTree(lims_sample.root))
data = data.decode('utf-8').replace('smp:sample', 'smp:samplecreation')
lims_sample.root = lims.post(uri=lims.get_uri(Sample._URI), data=data)
lims_sample._uri = lims_sample.root.attrib['uri']
```

Just wanted to share the research I did to make this work. If it's something you are interested in adding support for I'd be happy to work with you. Right now I don't feel like I understand the package well enough to suggest how best to add it tho.

**Comment by tcezard** [comment]
I created PR for this which should work. Let me know what you think.
