### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/genologics#192]
Hi,

it's great to see some updated to this package! Good job 👍 

I'm having some trouble understanding your versioning tho..

* In the package I see a reference to version "0.3.9" (https://github.com/SciLifeLab/genologics/blob/master/genologics/version.py)
* On PyPI the latest release (matching master I believe) is "0.3.11.post0"
* When I install the package my system tells me it's "0.0.0.post0"

So if I want to depend on the latest version or above, how should I do?

**Comment by withrocks** [comment]
Hi,

I had the same problem.

**What did I see:**
When running `pip freeze` I get the following: `genologics==0.0.0.post0`

**What did I expect to see**
`pip freeze` should return `genologics==0.3.12.post0`

**Details**
According to pip (by running `pip install genologics==notavail`) the latest version is `0.3.12.post0`

I actually have that version:
```
$ cat $(dirname $(python -c "import genologics; print genologics.__file__"))/version.py
__version__="0.3.12"
```
So it's just the metadata (returned by `pip freeze`) that's incorrect.

**Comment by Galithil** [comment]
I think I got this one, it will be fixed in the next release.
