### ISSUE TITLE
Consider switching to logbook

### ISSUE THREAD

**Issue by alneberg** [SciLifeLab/genologics#26]
"Logbook should meet your needs and could better integrate with the rest of packages/scilifelab software. Please, give it a second look/read on the docs and compare it with the bcbio-nextgen logging module/code.". @brainstorm, I agree to this argument, you were just using different arguments before. I think the major argument is the integration with other scilifelab packages together with e-mail support. The code in EPP_logger will look rather similar.

**Comment by Galithil** [comment]
I did a powerpoint about why I dislike logbook. Unless there are serious reasons to switch, I would rather not.
Closing.
