### ISSUE TITLE
Update udfs with dates.

### ISSUE THREAD

**Issue by alneberg** [SciLifeLab/genologics#52]
The way dates are handled by the udfdictionary is strange. I don't know how to update a date contained in a udf:

    one_process.udf['Finish Date'] = one_process.udf['Finish Date']

gives:
    
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-58-fc853b8bab69> in <module>()
    ----> 1 one_process.udf['Finish Date'] = one_process.udf['Finish Date']
    
    /Users/johannesalneberg/.virtualenvs/genologics-lims/lib/python2.7/site-packages/genologics-v0.2.3_202_gd058acf-py2.7.egg/genologics/entities.pyc in     __get__(self, instance, cls)
        321     def __get__(self, instance, cls):
        322         instance.get()
    --> 323         self.value = UdfDictionary(instance, udt=self._UDT)
        324         return self.value
        325 
    
    /Users/johannesalneberg/.virtualenvs/genologics-lims/lib/python2.7/site-packages/genologics-v0.2.3_202_gd058acf-py2.7.egg/genologics/entities.pyc in __init__(self, instance, udt)
        171         self._udt = udt
        172         self._update_elems()
    --> 173         self._prepare_lookup()
        174 
        175     def get_udt(self):

    /Users/johannesalneberg/.virtualenvs/genologics-lims/lib/python2.7/site-packages/genologics-v0.2.3_202_gd058acf-py2.7.egg/genologics/entities.pyc in _prepare_lookup(self)
        218                 value = value == 'true'
        219             elif type == 'date':
    --> 220                 value = datetime.date(*time.strptime(value, "%Y-%m-%d")[:3])
        221             self._lookup[elem.attrib['name']] = value
        222 

    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.pyc in _strptime_time(data_string, format)
        452 
        453 def _strptime_time(data_string, format="%a %b %d %H:%M:%S %Y"):
    --> 454     return _strptime(data_string, format)[0]

    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.pyc in _strptime(data_string, format)
        326     if len(data_string) != found.end():
        327         raise ValueError("unconverted data remains: %s" %
    --> 328                           data_string[found.end():])
        329     year = 1900
        330     month = day = 1

    ValueError: unconverted data remains:  00:00:00

Using a tuple or a plain string does not work either.

**Comment by Galithil** [comment]
a udf typed as "date" expects a datetime.date object.
As such, if you wanted to update a date in udf, here's how to do it (assuming import datetime): 
one_process.udf['Finish Date']=datetime.datetime.strptime('2015-07-31','%Y-%m-%d').date()
-> read the date with strptime and make it a datetime object
-> turn it into a date object
