### ISSUE TITLE
problem i copy_reference_genome.py

### ISSUE THREAD

**Issue by rikerl-scilifelab** [SciLifeLab/genologics#55]
Får ett felmeddelande när jag försöker köra sciptet på clinical instansen av clarity lims.

Den hittar inte log-filen och anger sökvägen utan / i början

.genologicsrc filens innehåll
[genologics]
BASEURI=https://clinical-lims.scilifelab.se
USERNAME=anändare
PASSWORD=lösenord
[logging]
MAIN_LOG=/home/glsai/clinical_main_log.txt

**Comment by Galithil** [comment]
I believe you need to create the logfile by yourself first.
